//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLFoodAnalyzerClient.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLFoodAnalyzerClient.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept settings.
        /// </summary>
        internal static string AcceptSettings {
            get {
                return ResourceManager.GetString("AcceptSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLFoodAnalyzer.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The picture has been sent to the server, wait for the results&lt;br/&gt;.
        /// </summary>
        internal static string AttachedAPicture {
            get {
                return ResourceManager.GetString("AttachedAPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text has been sent to the server, wait for the results.&lt;br/&gt;.
        /// </summary>
        internal static string AttachedAText {
            get {
                return ResourceManager.GetString("AttachedAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Settings.
        /// </summary>
        internal static string ChatSettings {
            get {
                return ResourceManager.GetString("ChatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the connection.
        /// </summary>
        internal static string CheckTheConnection {
            get {
                return ResourceManager.GetString("CheckTheConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default theme.
        /// </summary>
        internal static string DefaultTheme {
            get {
                return ResourceManager.GetString("DefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Agreement
        ///This License Agreement (the &quot;Agreement&quot;) is a legal agreement between you and DKAVrZoV65F for the use of the ML Food Analyzer software (the &quot;Software&quot;). By using the Software, you agree to comply with the terms of this Agreement.
        ///1. License grant
        ///In accordance with the terms and conditions of this Agreement, DKAVrZoV65F grants you a non-exclusive, non-transferable license to use the Program for personal, non-commercial purposes.
        ///2. Description of rights and restrictions
        ///The software i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescriptionPolicy {
            get {
                return ResourceManager.GetString("DescriptionPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Host Unreachable.
        /// </summary>
        internal static string DestinationHostUn {
            get {
                return ResourceManager.GetString("DestinationHostUn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the IP address.
        /// </summary>
        internal static string EnterTheIp {
            get {
                return ResourceManager.GetString("EnterTheIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password.
        /// </summary>
        internal static string EnterThePassword {
            get {
                return ResourceManager.GetString("EnterThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the port.
        /// </summary>
        internal static string EnterThePort {
            get {
                return ResourceManager.GetString("EnterThePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the text.
        /// </summary>
        internal static string EnterTheText {
            get {
                return ResourceManager.GetString("EnterTheText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username.
        /// </summary>
        internal static string EnterTheUserName {
            get {
                return ResourceManager.GetString("EnterTheUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the server!&lt;br/&gt;.
        /// </summary>
        internal static string ErrorConToServ {
            get {
                return ResourceManager.GetString("ErrorConToServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered username or password is incorrect.
        /// </summary>
        internal static string ErrorLogIn {
            get {
                return ResourceManager.GetString("ErrorLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description has not been updated.
        /// </summary>
        internal static string ErrorUpdateDescr {
            get {
                return ResourceManager.GetString("ErrorUpdateDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error With IP or port.
        /// </summary>
        internal static string ErrorWithIPOrPort {
            get {
                return ResourceManager.GetString("ErrorWithIPOrPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning robots using artificial intelligence can automatically identify and remove garbage, which greatly simplifies the cleaning process and reduces the likelihood of environmental pollution..
        /// </summary>
        internal static string ExampleText {
            get {
                return ResourceManager.GetString("ExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address:.
        /// </summary>
        internal static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        internal static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image must not exceed 8MB! You are uploading a picture with the size .
        /// </summary>
        internal static string LimitImage {
            get {
                return ResourceManager.GetString("LimitImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address has been copied to the clipboard..
        /// </summary>
        internal static string MailMessage {
            get {
                return ResourceManager.GetString("MailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainPage.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLModel.
        /// </summary>
        internal static string MLModel {
            get {
                return ResourceManager.GetString("MLModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I read policy.
        /// </summary>
        internal static string PolicyAccept {
            get {
                return ResourceManager.GetString("PolicyAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for the server is saved.
        /// </summary>
        internal static string PSWDServer {
            get {
                return ResourceManager.GetString("PSWDServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application for the changes to take effect..
        /// </summary>
        internal static string ReloadApp {
            get {
                return ResourceManager.GetString("ReloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the login?.
        /// </summary>
        internal static string SaveLogin {
            get {
                return ResourceManager.GetString("SaveLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the password.
        /// </summary>
        internal static string SavePSWD {
            get {
                return ResourceManager.GetString("SavePSWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an action.
        /// </summary>
        internal static string SelectAnAction {
            get {
                return ResourceManager.GetString("SelectAnAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send picture.
        /// </summary>
        internal static string SendPicture {
            get {
                return ResourceManager.GetString("SendPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send text.
        /// </summary>
        internal static string SendText {
            get {
                return ResourceManager.GetString("SendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: .
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description has been successfully updated.
        /// </summary>
        internal static string SuccessUpdateDescr {
            get {
                return ResourceManager.GetString("SuccessUpdateDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a picture.
        /// </summary>
        internal static string TakeAPicture {
            get {
                return ResourceManager.GetString("TakeAPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat, communication with the server.
        /// </summary>
        internal static string TipChat {
            get {
                return ResourceManager.GetString("TipChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the password you entered.
        /// </summary>
        internal static string TipDisplayPassword {
            get {
                return ResourceManager.GetString("TipDisplayPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username to which your account was registered.
        /// </summary>
        internal static string TipLogIn {
            get {
                return ResourceManager.GetString("TipLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password that you entered during registration.
        /// </summary>
        internal static string TipPassword {
            get {
                return ResourceManager.GetString("TipPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On some servers, you need to specify a password to encrypt the text.
        /// </summary>
        internal static string TipPasswordServer {
            get {
                return ResourceManager.GetString("TipPasswordServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves your username and password on your device.
        /// </summary>
        internal static string TipSaveLogIn {
            get {
                return ResourceManager.GetString("TipSaveLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a request or attach an image.
        /// </summary>
        internal static string TipWriteOrPickImg {
            get {
                return ResourceManager.GetString("TipWriteOrPickImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the password?.
        /// </summary>
        internal static string ViewThePassword {
            get {
                return ResourceManager.GetString("ViewThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
